FROM ubuntu:18.04

LABEL author="Petrochenko Kirill 221-352"

ENV TZ=Europe/Moscow  
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone  
RUN apt-get update  
RUN apt-get install qt5-default -y  
RUN apt-get install qtbase5-dev -y
RUN apt-get install qt5-qmake  
RUN apt-get install build-essential -y 

WORKDIR /root/
RUN mkdir Petrochenko
WORKDIR /root/Petrochenko/

COPY *.cpp /root/Petrochenko/
COPY *.h /root/Petrochenko/
COPY *.pro /root/Petrochenko/

RUN qmake -o myshop echoServer_351.pro 
RUN make myshop

EXPOSE 33333